default_install_hook_types:
  - commit-msg  # For conventional commit linting
  - pre-commit
default_stages:
  - pre-commit  # Run hooks, that do not say differently in this stage (allows to exclude duplicated runs for commit-msg stage)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c60c980e561ed3e73101667fe8365c609d19a438  # frozen: v0.15.9
    hooks:
      - id: ruff-check # Run the linter & fix fixable issues
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: 1f1b51c57b9a051a42d04deaa725c4c9a2d37aa0  # frozen: v0.1.66
    hooks:
      - id: rumdl
      - id: rumdl-fmt

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: aeba78b29b06233289a1a6ed80371a337e893e19  # frozen: v1.11.0
    hooks:
      - id: conventional-precommit-linter
        stages:
          - commit-msg
        args:
          - --allow-breaking
          - --scopes=bash,git,github,nushell,prek,python,starship,themes,vscode,windows-terminal,xonsh
          - --types=build,chore,ci,docs,feat,fix,refactor,revert,test  # Keep in sync with /.github/workflows/validate_pr_title.yml

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 99470f5e12208ff0fb17ab81c3c494f7620a1d8d  # frozen: v0.11.0
    hooks:
      - id: shellcheck
        args:
          - --exclude=SC1017 # Carriage return is handled by git & prek

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: e26a818fd47b4f33cefa99035d1265b0849f4b47  # frozen: v3.13.0-1
    hooks:
      - id: shfmt

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
    hooks:
      - id: actionlint

  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e  # frozen: v8.30.1
    hooks:
      - id: gitleaks
