name: Pre-commit auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: "42 12 * * 5" # Run weekly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit-update:
    name: Auto-update pre-commit hooks
    runs-on: [self-hosted, x64, linux, philips-code-hub, ubuntu-2404]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: pyproject.toml

      - name: Install prek
        uses: j178/prek-action@9d6a3097e0c1865ecce00cfb89fe80f2ee91b547 # v1.0.12
        with:
          install-only: true  # Do not `prek run`

      - name: Update pre-commit hooks
        run: prek autoupdate --freeze

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          branch: pre-commit/autoupdate
          title: "build(deps): Update pre-commit hooks"
          commit-message: "build(deps): Update pre-commit hooks"
          body: ""  # Empty
          labels: dependencies
