name: Pre-commit auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: "42 12 * * 5" # Run weekly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit-update:
    name: Auto-update pre-commit hooks
    runs-on: [self-hosted, x64, linux, philips-code-hub]
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version-file: pyproject.toml

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Update pre-commit hooks
        run: pre-commit autoupdate --freeze  # Use hashes for versions

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          branch: pre-commit/autoupdate
          title: "build(deps): Update pre-commit hooks"
          commit-message: "build(deps): Update pre-commit hooks"
          body: # Empty
          labels: dependencies
