name: Validate PR Title

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened # Also validate when PR is reopened, since the title might have been changed in the meantime.
      - synchronize

permissions: {}

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # To add CC-scope-based labels to the PR
    steps:
      - name: Check for Conventional Commit PR title
        uses: ytanikin/pr-conventional-commits@639145d78959c53c43112365837e3abd21ed67c1 # v1.5.2
        with:
          task_types: '["build", "chore", "ci", "docs", "feat", "fix", "refactor", "revert", "test"]'  # Keep in sync with /.pre-commit-config.yaml
          add_scope_label: true
